### PR TITLE
Fix export of all collections

### LINKED ISSUE #23: Zotelo is incompatible with Zotero 4.0.27.1
The most recent Zotero update breaks zotelo. When trying to export the bibliography I get the following error:

    !!! TypeError: this._export is undefined
    
    Details:

### PR DESCRIPTION
**Pull request by mliertzer**
Note, that the issue only occurred when exporting the whole bibliography.

Fixes #23

### CODE REVIEW

**Comment by vspinu** [comment]
Is this backward compatible? You said only the most recent `zotero` was affected.

**Comment by vspinu** [comment]
I have checked it out. 4.0.27.1 is not even the most recent version. Thanks, it works for me!

**Comment by mliertzer** [comment]
The change in Zotero happened in 4.0.27 released on 30th of June. The
commit works for all later releases. However, for users who didn't
update yet to 4.0.27+, the export of the whole library will most likely
fail as the setLibrary function wasn't defined before.

Since Zotero auto-updates, this shouldn't be a big issue, although one
could note in the README that zotelo requires zotero 4.0.27+.

**Comment by vspinu** [comment]
> However, for users who didn't update yet to 4.0.27+, the export of the whole library will most likely fail as the setLibrary function wasn't defined before.

I am 100% sure this worked in the beginning. I was routinely exporting the whole collection.  

> Since Zotero auto-updates, this shouldn't be a big issue,

Indeed!

**Comment by mliertzer** [comment]
On 08/08/15 14:08, Vitalie Spinu wrote:
>     However, for users who didn't update yet to 4.0.27+, the export of
>     the whole library will most likely fail as the setLibrary function
>     wasn't defined before.
> 
> I am 100% sure this worked in the beginning. I was routinely exporting
> the whole collection.

I meant that with the new patch, it will fail for older versions of
Zotero, but work for versions 4.0.27+. Without the patch, it is the
other way around.

**Pull request merged**
